# Generated by Django 5.2.4 on 2025-09-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_utilisateur_photo_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='numero_membre',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Numero Membre'),
        ),
    ]
