# Generated by Django 5.2.4 on 2025-11-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0004_utilisateur_numero_membre'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='date_de_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
