# Generated by Django 5.2.4 on 2025-12-03 12:55

import utilisateurs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0007_usersession_delete_emailotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='numero_membre',
            field=models.CharField(blank=True, default=utilisateurs.models.generer_numero_membre, max_length=30, null=True, unique=True, verbose_name='Numero Membre'),
        ),
    ]
