# Generated by Django 5.2.4 on 2026-02-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0008_alter_utilisateur_numero_membre'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='last_nouveaute_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
