# Generated by Django 5.2.4 on 2026-03-29 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0010_alter_utilisateur_role_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='utilisateurs.permission'),
        ),
    ]
