# Generated by Django 5.2.4 on 2026-04-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0011_permission_utilisateur_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('EMPRUNT', 'Emprunt'), ('RESERVATION', 'Réservation'), ('AUTRE', 'Autre'), ('RETOUR', 'Retour livre'), ('ANNULATION', 'Annulation'), ('EXPORT', 'Exportation données'), ('Autre', 'Autre')], max_length=20),
        ),
    ]
