# Generated by Django 5.2.4 on 2026-05-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0012_alter_activitylog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Email vérifié'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Compte approuvé'),
        ),
    ]
