# Generated by Django 5.2.4 on 2026-05-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0013_utilisateur_email_verified_utilisateur_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='code_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
