# Generated by Django 5.2.4 on 2025-08-02 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('BIBLIOTHECAIRE', 'Bibliothecaire'), ('ASSISTANT', 'Assistant'), ('AGENT_SECURITE', 'Agent de securite')], max_length=30)),
                ('date_embauche', models.DateField()),
                ('salaire_mensuel', models.DecimalField(decimal_places=2, max_digits=6)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
    ]
