# Generated by Django 5.2.4 on 2025-09-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
