# Generated by Django 5.2.4 on 2025-08-04 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='livre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='livres.livre'),
        ),
    ]
