# Generated by Django 5.2.4 on 2025-09-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0003_emprunt_livre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='emprunt',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'EN COURS'), ('retourne', 'RETOURNE'), ('retard', 'RETARD')], default='en_cours', max_length=30),
        ),
        migrations.AddField(
            model_name='livre',
            name='resume',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='penalite',
            name='date_paiement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livre',
            name='tags',
            field=models.ManyToManyField(blank=True, to='livres.tags'),
        ),
    ]
