# Generated by Django 5.2.4 on 2025-10-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0004_tags_emprunt_statut_livre_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='lecture_en_ligne',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
