# Generated by Django 5.2.4 on 2025-10-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0005_livre_lecture_en_ligne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='isbn',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
