# Generated by Django 5.2.4 on 2025-10-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0006_alter_livre_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='auteur',
            field=models.CharField(max_length=500),
        ),
    ]
