# Generated by Django 5.2.4 on 2025-10-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0007_alter_livre_auteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='nom',
            field=models.CharField(max_length=255),
        ),
    ]
