# Generated by Django 5.2.4 on 2025-10-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0008_alter_categorie_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='titre',
            field=models.CharField(max_length=500),
        ),
    ]
