# Generated by Django 5.2.4 on 2025-12-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0009_alter_livre_titre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre',
            name='disponible',
        ),
        migrations.AddField(
            model_name='livre',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
