# Generated by Django 5.2.4 on 2026-02-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0011_emprunt_valide_par'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='email_retard_envoye',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emprunt',
            name='notification_retard_envoye',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'EN COURS'), ('retourne', 'RETOURNE')], default='en_cours', max_length=30),
        ),
    ]
