# Generated by Django 5.2.4 on 2026-02-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0012_emprunt_email_retard_envoye_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='date_ajout_livre',
            field=models.DateField(auto_now=True),
        ),
    ]
