# Generated by Django 5.2.4 on 2026-03-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0013_livre_date_ajout_livre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='date_ajout_livre',
            field=models.DateField(auto_now_add=True),
        ),
    ]
