# Generated by Django 5.2.4 on 2026-03-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0014_alter_livre_date_ajout_livre'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='est_nouveau',
            field=models.BooleanField(default=True),
        ),
    ]
