# Generated by Django 5.2.4 on 2026-04-23 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0017_objectiflecture_delete_penalite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre',
            name='lecture_en_ligne',
        ),
    ]
