# Generated by Django 5.2.4 on 2025-09-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En_ATTENTE'), ('confirmee', 'CONFIRMEE'), ('annulee', 'ANNULEE'), ('expiree', 'EXPIREE')], default='en_attente', max_length=20),
        ),
    ]
