# Generated by Django 5.2.4 on 2025-10-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_reservation_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='type_reservation',
            field=models.CharField(choices=[('physique', 'Physique'), ('en_ligne', 'En_ligne')], default='Physique', max_length=30),
        ),
    ]
