# Generated by Django 5.2.4 on 2025-10-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_reservation_type_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_confirmation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='livre_demande',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='message_utilisateur',
            field=models.TextField(blank=True, null=True),
        ),
    ]
