# Generated by Django 5.2.4 on 2025-12-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_alter_reservation_date_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='livre_demande',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En_ATTENTE'), ('confirmee', 'CONFIRMEE'), ('annulee', 'ANNULEE'), ('expiree', 'EXPIREE'), ('trasforme_en_emprunt', 'Tranformee en emprunt')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='type_reservation',
            field=models.CharField(choices=[('physique', 'Physique'), ('en_ligne', 'En_ligne')], default='physique', max_length=30),
        ),
    ]
