# Generated by Django 5.2.4 on 2025-12-12 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_remove_reservation_livre_demande_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='confirme',
        ),
    ]
