# Generated by Django 5.2.4 on 2026-01-31 00:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_remove_reservation_confirme'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='reservation',
            name='qr_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En_ATTENTE'), ('confirmee', 'CONFIRMEE'), ('annulee', 'ANNULEE'), ('expiree', 'EXPIREE'), ('transforme_en_emprunt', 'Tranformee en emprunt')], default='en_attente', max_length=50),
        ),
    ]
