# Generated by Django 5.2.4 on 2026-01-31 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_remove_reservation_qr_code_reservation_qr_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='qr_code',
        ),
    ]
