# Generated by Django 5.2.4 on 2026-02-11 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_reservation_valide_par_alter_reservation_qr_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='valide_par',
        ),
    ]
