# Generated by Django 5.2.4 on 2025-09-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='type_notifications',
            field=models.CharField(choices=[('retard', 'RETARD DE RETOUR'), ('disponibilite', 'LIVRE DISPONIBLE'), ('nouveaute', 'UN NOUVEAU LIVRE AJOUTÉ')], default='disponibilite', max_length=25),
        ),
    ]
