# Generated by Django 5.2.4 on 2026-01-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notifications_link_notifications_type_notifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifications',
            options={'ordering': ['-date_envoi']},
        ),
        migrations.AlterField(
            model_name='notifications',
            name='type_notifications',
            field=models.CharField(choices=[('retard', 'RETARD DE RETOUR'), ('disponibilite', 'LIVRE DISPONIBLE'), ('reservation', 'STATUT DE RÉSERVATION'), ('validation', 'VALIDATION RESERVATION'), ('annulation', 'ANNULATION RESERVATION')], default='disponibilite', max_length=25),
        ),
    ]
